---
irida:
  config:
    sequence.file.base.directory: "{{ paths.sequences }}"
    reference.file.base.directory: "{{ paths.reference }}"
    output.file.base.directory: "{{ paths.output }}"
    assembly.file.base.directory: "{{ paths.assembly }}"
    file.processing.core.size: 4
    file.processing.max.size: 8
    file.processing.queue.capacity: 512
    file.processing.process: true
    jdbc.driver: "com.mysql.jdbc.Driver"
    hibernate.dialect: "org.hibernate.dialect.MySQL55Dialect"
    liquibase.update.database.schema: true
    jdbc.pool.initialSize: 10
    jdbc.pool.maxActive: 20
    jdbc.pool.testOnBorrow: true
    jdbc.pool.testOnReturn: true
    jdbc.pool.testWhileIdle: true
    jdbc.pool.validationQuery: "select 1"
    jdbc.pool.maxWait: 10000
    jdbc.pool.removeAbandoned: true
    jdbc.pool.logAbandoned: true
    jdbc.pool.removeAbandonedTimeout: 60
    jdbc.pool.maxIdle: 10
    security.password.expiry: -1
    galaxy.execution.url: "http://{{ containers.galaxy.name }}/"
    galaxy.execution.dataStorage: local
    irida.workflow.max-running: 4
    irida.scheduled.subscription.cron: "0 0 0 * * *"
    irida.scheduled.threads: 2
    ncbi.upload.host: localhost
    ncbi.upload.user: test
    ncbi.upload.password: password
    ncbi.upload.baseDirectory: tmp
    ncbi.upload.port: 21
    ncbi.upload.namespace: IRIDA
