---
- name: Configure server
  xml:
    path: /usr/local/tomcat/conf/server.xml
    xpath: "{{ item.xpath }}"
    attribute: "{{ item.attribute }}"
    value: "{{ item.value }}"
  loop:
    - xpath: /Server/Service/Engine/Host
      attribute: workDir
      value: "{{ paths.tmp }}/tomcat/"
    - xpath: /Server/Service/Connector
      attribute: port
      value: "8080"
    - xpath: /Server/Service/Connector
      attribute: secure
      value: "true"
    - xpath: /Server/Service/Engine/Host/Valve[@className='org.apache.catalina.valves.AccessLogValve']
      attribute: requestAttributesEnabled
      value: "true"

- name: Enable x-forwarded-for
  xml:
    path: /usr/local/tomcat/conf/server.xml
    xpath: /Server/Service/Engine/Host
    add_children:
    - Valve:
        className: "org.apache.catalina.valves.RemoteIpValve"
        protocolHeader: "x-forwarded-proto"
        internalProxies: ".*"
        # remoteIpHeader: "x-forwarded-for"
        # proxiesHeader: "x-forwarded-by"
        # protocolHeaderHttpsValue: "https"

- name: Generate irida.conf
  vars:
    config: "{{ irida.config }}"
  template:
    src: conf.j2
    dest: "{{ paths.config }}/irida.conf"
    mode: u=rw,g=r,o=r

- name: Dump irida config to yaml
  copy:
    content: "{{ irida.config | to_nice_yaml }}"
    dest: "{{ paths.config }}/irida_conf.yml"
    mode: u=rw,g=r,o=r

- name: Generate web.conf
  vars:
    config: "{{ irida.web }}"
  template:
    src: conf.j2
    dest: "{{ paths.config }}/web.conf"
    mode: u=rw,g=r,o=r

- name: Dump web config to yaml
  copy:
    content: "{{ irida.web | to_nice_yaml }}"
    dest: "{{ paths.config }}/web_conf.yml"
    mode: u=rw,g=r,o=r

- name: Read irida version
  xml:
    path: "{{ playbook_dir }}/irida/pom.xml"
    xpath: "/x:project/x:version"
    content: text
    namespaces:
      x: "http://maven.apache.org/POM/4.0.0"
  register: irida_version
  delegate_to: buildah_server

- name: Import irida.war and unpack
  unarchive:
    copy: yes
    src: "{{ playbook_dir }}/irida/target/irida-{{ (irida_version.matches[0].values() | list)[0] }}.war"
    dest: "{{ paths.app }}"
    mode: u=rwX,g=rX,o=rX

- name: Set permissions on unpacked files
  file:
    path: "{{ paths.app }}"
    state: directory
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Bundle tool list
  copy:
    src: "{{ playbook_dir }}/irida/target/tools-list.yml"
    dest: "{{ paths.config }}/tool-list.yml"
    mode: u=rw,g=r,o=r