name: Autobuild

on:
  create:
    tags:
      - 'v*'
  push:
    tags:
      - 'v*'
  pull_request:
    branch: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install buildah
      run: |
        . /etc/os-release
        sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${ID^}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
        wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${ID^}_${VERSION_ID}/Release.key -O Release.key
        sudo apt-key add - < Release.key
        sudo apt-get update -qq
        sudo apt-get -qq -y install buildah ansible
        sudo pip install docker
    - name: Build IRIDA
      run: ./irida.playbook.yml

    - name: Publish application
      run: "buildah push --creds ${{ secrets.DOCKERHUB_ID }}:${{ secrets.DOCKERHUB_TOKEN }} irida_app docker://docker.io/${{ secrets.DOCKERHUB_ID }}/irida_app:${{ github.ref }}"